import {state,$,api,esc,badge,date,today,title,field,area,select,table,formData,bindForm,empty,toast,wireButtons} from './ui.js';
import {unitRows,wirePortfolio} from './portfolio.js';

export function renderLearning(refresh){
 const d=state.data,page=state.page,staff=['admin','assessor'].includes(state.user.role);
 if(!d){$('#content').innerHTML=title('Your learning workspace','Everything you need to build skills and record progress.')+empty(state.user.role==='admin'?'Create a learner and enrol them on a course in Administration.':'No learners are assigned to this account. Ask your administrator for access.');return;}
 const completed=d.units.filter(u=>['assessed','verified'].includes(u.status)).length;
 const pct=d.units.length?Math.round(completed/d.units.length*100):0;
 const submitted=d.units.filter(u=>u.status==='submitted').length;
 const approved=d.hours.filter(h=>h.status==='approved').reduce((a,h)=>a+h.minutes,0)/60;
 const pendingHours=d.hours.filter(h=>h.status==='pending').length;
 const requiredAttendance=d.attendance.filter(a=>a.status!=='authorised');
 const attendance=requiredAttendance.length?Math.round(requiredAttendance.filter(a=>['present','late'].includes(a.status)).length/requiredAttendance.length*100):null;
 const next=d.reviews[0]?.next_date;
 const courseInfo=`<section class="notice"><a href="#" data-export="${state.lid}">Download learner record (JSON)</a><hr>${d.courses.map(c=>`<strong>${esc(c.title)}</strong><p>${esc(c.description)}</p>`).join('')||'No course enrolment yet.'}</section>`;
 if(page==='dashboard'){
  $('#content').innerHTML=title('Academy dashboard','Barbering training, practical evidence and learner progress.')+`
  ${courseInfo}<section class="hero"><div><p class="eyebrow">LEARNING JOURNEY</p><h2>${esc(d.learner.name)}’s training</h2><p>Build your portfolio, reflect on your practical work and keep moving towards your next milestone.</p></div><div><div class="big-percent">${pct}%</div><span class="small">${completed} of ${d.units.length} service records assessed</span></div></section>
  <div class="stats"><div class="stat"><p>Assessed records</p><strong>${completed}<span class="muted"> / ${d.units.length}</span></strong><span class="small">Includes IQA-verified records</span></div><div class="stat"><p>Awaiting assessment</p><strong>${submitted}</strong><span class="small">Submitted by learner</span></div><div class="stat"><p>Approved learning hours</p><strong>${approved.toFixed(1)}</strong><span class="small">${pendingHours} entries awaiting review</span></div><div class="stat"><p>Recorded attendance</p><strong>${attendance===null?'—':attendance+'%'}</strong><span class="small">Authorised absences excluded</span></div></div>
  <div class="grid-two"><section class="card"><div class="card-head"><h3>Your units</h3><span class="small">${d.units.length} records</span></div>${unitRows(d.units)||empty('Your course units will appear here.')}</section><div><section class="card"><p class="eyebrow muted">NEXT PROGRESS REVIEW</p><h2>${date(next)}</h2><p class="small">${next&&next<today()?'This review is due. Please contact your tutor.':'Your tutor will agree your review dates with you.'}</p></section><section class="card"><h3>Focus for your next session</h3><p class="prose">${esc(d.reviews[0]?.actions||'Bring your tools, review your feedback and record what you learn after each session.')}</p></section><section class="notice">Progress reflects assessed service records, not unit completion. It is not a qualification certificate or an awarding-body result.</section></div></div>`;
  wirePortfolio(refresh);
 }else if(page==='portfolio'){
  $('#content').innerHTML=title('E-portfolio','Your practical evidence, reflections and assessment feedback.')+courseInfo+`<section class="card">${unitRows(d.units)||empty('No units assigned.')}</section>`;wirePortfolio(refresh);
 }else if(page==='assessment'){
  const statuses=state.user.role==='iqa'?['assessed','iqa_action']:state.user.role==='admin'?['submitted','assessed','iqa_action']:['submitted','iqa_action'];
  $('#content').innerHTML=title('Assessment & quality','Review work for the selected learner. Decisions are recorded against your account.')+`<section class="card">${unitRows(d.units.filter(u=>statuses.includes(u.status)))||empty('No work waiting in this queue.')}</section>`;wirePortfolio(refresh);
 }else if(page==='attendance'){
  $('#content').innerHTML=title('Attendance','One academy attendance entry per learner, per day.')+(staff?`<details><summary>Record or correct attendance</summary><form id="attendance-form"><div class="form-grid">${field('day','Session date','date',today())}${select('status','Status',[['present','Present'],['late','Late'],['absent','Absent'],['authorised','Authorised absence']])}${field('minutes','Minutes attended','number','360')}${field('note','Note','text','',false)}</div><p class="small">For absence, enter 0 minutes. Saving an existing date updates that day and records an audit event.</p><button class="primary">Save attendance</button></form></details>`:'')+`<section class="card">${table(['Date','Status','Hours','Note'],d.attendance.map(a=>`<tr><td>${date(a.day)}</td><td>${badge(a.status)}</td><td>${(a.minutes/60).toFixed(1)}</td><td>${esc(a.note)}</td></tr>`).join(''))}</section>`;
  bindForm('attendance-form',async form=>{await api(`/api/learners/${state.lid}/attendance`,'POST',formData(form));toast('Attendance saved.');await refresh();});
 }else if(page==='hours'){
  $('#content').innerHTML=title('Learning hours','Record what you learned and how you will use it.')+`<section class="card"><h3>Approved hours by activity</h3>${['academy','placement','other'].map(k=>`<p>${esc(k)}: ${(d.hours.filter(h=>h.status==='approved'&&h.category===k).reduce((n,h)=>n+h.minutes,0)/60).toFixed(1)} hours</p>`).join('')}<p class="small">Academy attendance is reported separately and is not added again to these totals. VRQ weekly plan: 18 placement hours and 6 academy hours. These are academy targets, not automatic qualification credit.</p></section>`+(state.user.role==='learner'?`<details open><summary>Log learning</summary><form id="hours-form"><div class="form-grid">${field('day','Learning date','date',today())}${field('minutes','Minutes spent learning','number','60')}${select('category','Type of learning',[['academy','Academy training'],['placement','Placement / shadowing'],['other','Other learning']])}${select('course_id','Course',d.courses.map(c=>[c.id,c.title]))}</div>${area('activity','What did you do?')}${area('reflection','What did you learn and how will you apply it?')}<button class="primary">Submit hours for review</button></form></details>`:'')+`<div class="notice">Only approved entries count in the dashboard total. Your tutor decides which activities count towards your programme requirements.</div><section class="card">${table(['Date / duration','Activity & reflection','Status / feedback','Review'],d.hours.map(h=>`<tr><td>${date(h.day)}<br>${(h.minutes/60).toFixed(1)} hours</td><td><span class="pill">${esc(h.category)}</span> <strong>${esc(h.activity)}</strong><p>${esc(h.reflection)}</p></td><td>${badge(h.status)}<p>${esc(h.feedback)}</p></td><td>${staff&&h.status==='pending'?`<button data-hours="${h.id}" data-status="approved">Approve</button> <button data-hours="${h.id}" data-status="rejected">Reject</button>`:'—'}</td></tr>`).join(''))}</section>`;
  bindForm('hours-form',async form=>{await api(`/api/learners/${state.lid}/hours`,'POST',formData(form));toast('Hours submitted.');await refresh();});
  wireButtons('[data-hours]',async b=>{const feedback=prompt('Feedback for the learner (required):');if(!feedback?.trim())return;await api(`/api/hours/${b.dataset.hours}/review`,'POST',{status:b.dataset.status,feedback});toast('Hours reviewed.');await refresh();});
 }else if(page==='reviews'){
  $('#content').innerHTML=title('Progress reviews','Agree clear next steps and keep a record of your development.')+(staff?`<details><summary>Add progress review</summary><form id="review-form"><div class="form-grid">${field('review_date','Review date','date',today())}${field('next_date','Next review date','date')}</div>${area('strengths','Progress, strengths and support discussed')}${area('actions','Agreed actions — include owner and target dates')}<button class="primary">Save review</button></form></details>`:'')+d.reviews.map(r=>`<section class="card"><div class="card-head"><h3>Review · ${date(r.review_date)}</h3><span class="small">Next: ${date(r.next_date)}</span></div><h4>Progress & support</h4><p class="prose">${esc(r.strengths)}</p><h4>Agreed actions</h4><p class="prose">${esc(r.actions)}</p><p class="small">Recorded by ${esc(r.author)} · ${r.acknowledged?'Acknowledged by learner on '+date(r.acknowledged):'Awaiting learner acknowledgement'}</p>${state.user.role==='learner'&&!r.acknowledged?`<button data-ack="${r.id}">I have read this review</button>`:''}</section>`).join('')+(d.reviews.length?'':empty('No progress reviews recorded yet.'));
  bindForm('review-form',async form=>{await api(`/api/learners/${state.lid}/reviews`,'POST',formData(form));toast('Review saved.');await refresh();});
  wireButtons('[data-ack]',async b=>{await api(`/api/reviews/${b.dataset.ack}/acknowledge`,'POST',{});toast('Review acknowledged.');await refresh();});
 }else if(page==='exams'){
  const unique=[...new Map(d.units.map(u=>[u.unit_id,u])).values()];
  $('#content').innerHTML=title('Exam results','Record externally administered results. This app does not deliver awarding-body exams.')+(staff&&unique.length?`<details open><summary>Record an exam attempt</summary><form id="exam-form">${select('unit_id','Unit',unique.map(u=>[u.unit_id,u.course+' / '+u.ref]))}${field('day','Exam date','date',today())}${select('outcome','Outcome',[['pending','Pending'],['pass','Pass'],['fail','Fail']])}${field('reference','Result reference / correction reason')}<button class="primary">Save result</button></form></details>`:'')+`<section class="card">${table(['Unit','Date','Result','Reference'],d.exams.map(e=>`<tr><td>${esc(e.ref)} · ${esc(e.title)}</td><td>${date(e.day)}</td><td>${badge(e.outcome)}</td><td>${esc(e.reference)}</td></tr>`).join(''))}<p class="small">Results are append-only. Record a correction with its reason if a result was entered incorrectly. Earlier entries stay visible.</p></section>`;
  bindForm('exam-form',async form=>{await api(`/api/learners/${state.lid}/exams`,'POST',formData(form));toast('Exam result recorded.');await refresh();});
 }else if(page==='resources'){
  $('#content').innerHTML=title('Learning resources','Course notes and resources selected by your academy.')+d.resources.map(r=>`<section class="card"><span class="pill">${esc(r.course)}</span><h3>${esc(r.title)}</h3><p class="prose">${esc(r.body)}</p>${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Open resource ↗</a>`:''}</section>`).join('')+(d.resources.length?'':empty('Your academy has not added resources for this course yet.'));
 }
}
